twig:
  file_name_pattern: '*.twig'
  form_themes: ['bootstrap_5_layout.html.twig'] # ma config
  default_path: '%kernel.project_dir%/templates' # ma config

when@test:
  twig:
    strict_variables: true
