vich_uploader:
  db_driver: orm

  metadata:
    type: attribute

  mappings:
    document:
      uri_prefix: /uploads/documents
      upload_destination: '%kernel.project_dir%/public/uploads/documents'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
    imagedocument:
      uri_prefix: /images/pagegardes
      upload_destination: '%kernel.project_dir%/public/images/pagegardes'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
    avatar:
      uri_prefix: /images/avatars
      upload_destination: '%kernel.project_dir%/public/images/avatars'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
